In [1]:
## Packages
import pandas as pd
import numpy as np

In [28]:
## Import data stored in Git Hub
df_raw = pd.read_csv("election-results-2012-2024_with-all-party-totals.csv")
df_raw.head(10)

,level,county,county_fips,ctv,municipality,MCD_FIPS,reporting_unit,rep_unit_2024,PREDEM24,USSTOT24,...,GOVTOT14,PREDEM12,USSTOT12,USSDEM12,GOVREP12,GOVTOT12,PREREP12,GOVDEM12,PRETOT12,USSREP12
0,reporting unit,ADAMS,55001,T,ADAMS,5500100300,TOWN OF ADAMS WARDS 1-3,ADAMS - TOWN OF ADAMS WARDS 1-3,264,791,...,501.194313,358.037915,606.620853,335.909953,280.682464,526.464455,270.625592,239.781991,640.663507,260.611374
1,reporting unit,ADAMS,55001,T,BIG FLATS,5500107300,TOWN OF BIG FLATS WARDS 1 & 2,ADAMS - TOWN OF BIG FLATS WARDS 1-2,177,646,...,402.000000,282.000000,487.000000,281.000000,215.000000,390.000000,209.000000,168.000000,497.000000,180.000000
2,reporting unit,ADAMS,55001,T,COLBURN,5500116075,TOWN OF COLBURN WARD 1,ADAMS - TOWN OF COLBURN WARD 1,37,164,...,104.000000,63.000000,117.000000,69.000000,60.000000,107.000000,58.000000,46.000000,124.000000,45.000000
3,reporting unit,ADAMS,55001,T,DELL PRAIRIE,5500119575,TOWN OF DELL PRAIRIE WARDS 1 & 2,ADAMS - TOWN OF DELL PRAIRIE WARDS 1-3,379,1000,...,673.000000,429.000000,826.000000,406.000000,387.000000,670.000000,411.000000,277.000000,845.000000,408.000000
4,reporting unit,ADAMS,55001,T,EASTON,5500122000,TOWN OF EASTON WARD 1,ADAMS - TOWN OF EASTON WARD 1,199,647,...,389.000000,270.000000,497.000000,254.000000,204.000000,387.000000,237.000000,175.000000,512.000000,234.000000
5,reporting unit,ADAMS,55001,T,JACKSON,5500137625,TOWN OF JACKSON WARDS 1 & 2,ADAMS - TOWN OF JACKSON WARDS 1-2,277,764,...,462.000000,310.000000,565.000000,297.000000,263.000000,470.000000,253.000000,202.000000,567.000000,259.000000
6,reporting unit,ADAMS,55001,T,LEOLA,5500143425,TOWN OF LEOLA WARD 1,ADAMS - TOWN OF LEOLA WARD 1,34,173,...,122.000000,50.000000,150.000000,51.000000,98.000000,120.000000,102.000000,19.000000,154.000000,96.000000
7,reporting unit,ADAMS,55001,T,LINCOLN,5500144250,TOWN OF LINCOLN WARD 1,ADAMS - TOWN OF LINCOLN WARD 1,67,206,...,143.000000,84.000000,160.000000,82.000000,69.000000,135.000000,80.000000,64.000000,166.000000,69.000000
8,reporting unit,ADAMS,55001,T,MONROE,5500153725,TOWN OF MONROE WARD 1,ADAMS - TOWN OF MONROE WARD 1,120,327,...,216.000000,135.000000,261.000000,145.000000,132.000000,233.000000,126.000000,101.000000,263.000000,110.000000
9,reporting unit,ADAMS,55001,T,NEW CHESTER,5500156525,TOWN OF NEW CHESTER WARDS 1-3,ADAMS - TOWN OF NEW CHESTER WARDS 1-3,166,529,...,304.000000,266.000000,418.000000,231.000000,168.000000,333.000000,160.000000,160.000000,428.000000,175.000000

In [29]:
## Collapse data by FIPS code to get county-level counts
df_c = df_raw.groupby(['county_fips', 'county'], as_index = False).sum()
## Remove unnecessary columns
df_c = df_c.drop(columns = ['level', 'ctv', 'municipality', 'MCD_FIPS', 'reporting_unit', 'rep_unit_2024'])
## Round to nearest whole number
df_c = df_c.round(0)
df_c.head(10)

,county_fips,county,PREDEM24,USSTOT24,USSDEM24,USSREP24,PREREP24,PRETOT24,GOVTOT22,USSTOT22,...,GOVTOT14,PREDEM12,USSTOT12,USSDEM12,GOVREP12,GOVTOT12,PREREP12,GOVDEM12,PRETOT12,USSREP12
0,55001,ADAMS,4434,12735,4795,7539,7750,12843,9890.0,9866.0,...,8174.0,5537.0,9795.0,5156.0,4489.0,8246.0,4634.0,3652.0,10272.0,4394.0
1,55003,ASHLAND,4612,8836,4775,3844,4190,8948,7015.0,6986.0,...,6566.0,5399.0,8388.0,5306.0,2598.0,6827.0,2820.0,4174.0,8372.0,2912.0
2,55005,BARRON,8941,26478,9352,16399,16744,26827,20133.0,20079.0,...,16749.0,10890.0,22285.0,10644.0,10420.0,17584.0,11443.0,7015.0,22692.0,10805.0
3,55007,BAYFIELD,6107,11152,6260,4697,4860,11205,9291.0,9280.0,...,8023.0,6033.0,9630.0,6017.0,3269.0,8216.0,3603.0,4889.0,9788.0,3476.0
4,55009,BROWN,67910,147828,67763,76706,79115,149267,114209.0,113883.0,...,100294.0,62528.0,125978.0,60410.0,61970.0,103895.0,64837.0,41239.0,128931.0,61839.0
5,55011,BUFFALO,2765,8019,2913,4898,5213,8100,6138.0,6118.0,...,5504.0,3570.0,6877.0,3366.0,3403.0,5599.0,3364.0,2148.0,7039.0,3284.0
6,55013,BURNETT,3676,10727,3731,6743,7005,10816,8142.0,8196.0,...,6537.0,3986.0,8438.0,3996.0,3998.0,6576.0,4550.0,2536.0,8677.0,4288.0
7,55015,CALUMET,12922,32655,12844,19061,19474,32893,25025.0,24951.0,...,21614.0,11489.0,25972.0,10989.0,15004.0,22638.0,14539.0,7515.0,26420.0,14053.0
8,55017,CHIPPEWA,14575,38061,14879,22201,23414,38435,29205.0,28827.0,...,24506.0,15237.0,30500.0,14774.0,14877.0,25556.0,15322.0,10419.0,30932.0,14677.0
9,55019,CLARK,4509,15165,4822,9918,10485,15316,11693.0,11655.0,...,11391.0,6172.0,13547.0,6159.0,8133.0,11851.0,7412.0,3618.0,13801.0,6875.0

In [30]:
# Calculate percentage democratic and republican in 2024 and 2020

df_c['PREDEMPCT24'] = df_c['PREDEM24']/df_c['USSTOT24']*100
df_c['PREREPPCT24'] = df_c['PREREP24']/df_c['USSTOT24']*100
df_c['PREDEMPCT20'] = df_c['PREDEM20']/df_c['PRETOT20']*100
df_c['PREREPPCT20'] = df_c['PREREP20']/df_c['PRETOT20']*100

# Calculate the percentage point change for dems and 
df_c['DEM_PP_CHANGE'] = df_c['PREDEMPCT24'] - df_c['PREDEMPCT20'] 
df_c['REP_PP_CHANGE'] = df_c['PREREPPCT24'] - df_c['PREREPPCT20'] 
df_c['PP_CHANGE'] = df_c['REP_PP_CHANGE'] - df_c['DEM_PP_CHANGE']
df_c["Republican swing"] = df_c['PP_CHANGE']/2
df_c["Democrat swing"] = df_c['PP_CHANGE']/-2
df_c['Swing_party'] = np.where(df_c['DEM_PP_CHANGE'] >= df_c['REP_PP_CHANGE'], "Democrat", "Republican")



df_c.to_csv('data_arrows.csv', index=False)

df_c.head()

,county_fips,county,PREDEM24,USSTOT24,USSDEM24,USSREP24,PREREP24,PRETOT24,GOVTOT22,USSTOT22,...,PREDEMPCT24,PREREPPCT24,PREDEMPCT20,PREREPPCT20,DEM_PP_CHANGE,REP_PP_CHANGE,PP_CHANGE,Republican swing,Democrat swing,Swing_party
0,55001,ADAMS,4434,12735,4795,7539,7750,12843,9890.0,9866.0,...,34.817432,60.855909,36.631900,62.291190,-1.814468,-1.435281,0.379187,0.189594,-0.189594,Republican
1,55003,ASHLAND,4612,8836,4775,3844,4190,8948,7015.0,6986.0,...,52.195564,47.419647,54.824712,43.862053,-2.629148,3.557594,6.186742,3.093371,-3.093371,Republican
2,55005,BARRON,8941,26478,9352,16399,16744,26827,20133.0,20079.0,...,33.767656,63.237405,36.273968,62.349089,-2.506312,0.888316,3.394628,1.697314,-1.697314,Republican
3,55007,BAYFIELD,6107,11152,6260,4697,4860,11205,9291.0,9280.0,...,54.761478,43.579627,56.498162,42.435662,-1.736684,1.143965,2.880649,1.440325,-1.440325,Republican
4,55009,BROWN,67910,147828,67763,76706,79115,149267,114209.0,113883.0,...,45.938523,53.518278,45.488189,52.682229,0.450334,0.836049,0.385715,0.192858,-0.192858,Republican

In [31]:

# Find the largest and smallest values in column 'A'
largest = df_c.nlargest(7, 'Republican swing')
smallest = df_c.nsmallest(4, 'Republican swing')

# Append together
df_swings = pd.concat([largest, smallest])


#select columns to keep 
df_swings = df_swings[['county_fips', 'county', 'Republican swing', 'Swing_party']]

wisc_row = {'county_fips': 55000, 'county': "STATE of WISCONSIN", "Republican Swing": 0.00, 'Swing_party': "STATEWIDE"}
#df_swings = pd.concat([df_swings, wisc_row], ignore_index=True)
df_swings.loc[len(df_swings)] = new_row

df_swings.head(10)

NameError: name 'new_row' is not defined

In [ ]:
## Calculate new colums 

#Votes for Kamala Harris 2024 - Tammy Baldwin2024
df_c['DIFFDEM24'] = df_c['PREDEM24'] - df_c['USSDEM24']
#Votes for Donald Trump 2024 - Eric Hovde 2024
df_c['DIFFREP24'] = df_c['PREREP24'] - df_c['USSREP24'] 
#Votes for Kamala Harris 2024 - Joe Biden 2020
df_c['DIFF_PRE_DEM_24to20'] = df_c['PREDEM24'] - df_c['PREDEM20']
#Votes for Donald Trump 2024 - Donald Trump Trump 2020
df_c['DIFF_PRE_REP_20to24'] = df_c['PREREP24'] - df_c['PREREP20']



#Select the columns of interest, sort by preferred variable DIFF_PRE_REP_20to24
df_f = df_c[['county_fips', 'county', 'DIFFDEM24', 'DIFFREP24', 'DIFF_PRE_DEM_24to20', 'DIFF_PRE_REP_20to24']].sort_values(by = ['DIFF_PRE_REP_20to24'], ascending = False)

#df_f.info()
df_f.head(10)

,county_fips,county,DIFFDEM24,DIFFREP24,DIFF_PRE_DEM_24to20,DIFF_PRE_REP_20to24
12,55025,DANE,294,692,13834.0,6656.0
31,55063,LA CROSSE,-260,1501,1162.0,3563.0
40,55079,MILWAUKEE,880,6317,-1271.0,3527.0
55,55109,ST. CROIX,78,693,678.0,3328.0
4,55009,BROWN,147,2409,2397.0,3241.0
67,55133,WAUKESHA,2694,-823,4549.0,3092.0
53,55105,ROCK,-436,2119,-16.0,3079.0
64,55127,WALWORTH,279,906,354.0,2730.0
29,55059,KENOSHA,-121,2313,-368.0,2503.0
44,55087,OUTAGAMIE,242,1750,1770.0,2441.0

In [ ]:
## Chart 1
#pip install "altair[all]" in linux
import altair as alt



alt.Chart(df_f).mark_bar().encode(
    x="DIFF_PRE_REP_20to24",
    y=alt.Y("county").sort("x")
)

alt.Chart(df_f).mark_bar().encode(
    y="DIFF_PRE_REP_20to24",
    x=alt.Y("county").sort("y", order = "descending")
)

alt.Chart(df_f).mark_bar().encode(
    y="DIFF_PRE_REP_20to24",
    x=alt.Y("county", 
            sort=alt.EncodingSortField('y', order='descending'))
)

alt.Chart(...)

In [ ]:
# pip install censusdis

import censusdis.data as ced
# American Community Survey 5-Year Data
# https://www.census.gov/data/developers/data-sets/acs-5year.html
DATASET = "acs/acs5"

# The year we want data for.
YEAR = 2020

# This are the census variables for total population and median household income.
# For more details, see
#
#     https://api.census.gov/data/2020/acs/acs5/variables.html,
#     https://api.census.gov/data/2020/acs/acs5/variables/B01003_001E.html, and
#     https://api.census.gov/data/2020/acs/acs5/variables/B19013_001E.html.
#
TOT_POP = "B01003_001E"
MED_HH_INC = "B19013_001E"
WHITE_ALONE = "B02001_002E"
#LAND_AREA = "ALAND"

# The variables we are going to query.
VARIABLES = ["NAME", TOT_POP, MED_HH_INC, WHITE_ALONE]

In [99]:
#Download census county-level demographic data
from censusdis import states

df_counties = ced.download(
    DATASET,
    YEAR,
    VARIABLES,
    state=states.WI,
    county="*",
)
df_counties.head(10)



df_counties["county_fips"] = df_counties["STATE"] + df_counties["COUNTY"]
df_counties["county_fips"] = pd.to_numeric(df_counties["county_fips"])


df_counties.columns = ['STATE', 'COUNTY', 'NAME', 'TOT_POP', 'MED_HH_INC', 'WHITE_POP', 'county_fips']

df_counties2 = df_counties[['NAME', 'TOT_POP', 'MED_HH_INC', 'WHITE_POP', 'county_fips']]

df_counties2.head()

                        NAME  TOT_POP  MED_HH_INC  WHITE_POP  county_fips
0  Ashland County, Wisconsin    15524       47869      13025        55003
1   Barron County, Wisconsin    45182       52346      42535        55005
2    Brown County, Wisconsin   262559       64728     220020        55009
3  Buffalo County, Wisconsin    13087       58364      12631        55011
4  Calumet County, Wisconsin    50005       76065      46723        55015

In [100]:
import requests
import pandas as pd

# Census API key (replace with your own)
api_key = "3d06f31ff8f016ac0ac729868edc18ea956bc5a6"

# API endpoint
base_url = "https://api.census.gov/data/2021/acs/acs5"

# Variables we need
variables = [
    "NAME",
    "B15003_001E",  # Total population 25 years and over
    "B15003_022E",  # Bachelor's degree
    "B15003_023E",  # Master's degree
    "B15003_024E",  # Professional school degree
    "B15003_025E"   # Doctorate degree
]

# Construct the API request
params = {
    "get": ",".join(variables),
    "for": "county:*",
    "in": "state:55",  # FIPS code for Wisconsin
    "key": api_key
}

# Make the API request
response = requests.get(base_url, params=params)
data = response.json()


# Convert to DataFrame
df_ed = pd.DataFrame(data[1:], columns=data[0])

# Create 5-digit FIPS code
df_ed["county_fips"] = df_ed["state"] + df_ed["county"]

# Convert relevant columns to numeric
for col in df_ed.columns[1:]:
    df_ed[col] = pd.to_numeric(df_ed[col])

# Calculate percentage
df_ed["pct_bachelors"] = (
    df_ed["B15003_022E"] + df_ed["B15003_023E"] + df_ed["B15003_024E"] + df_ed["B15003_025E"]
) / df_ed["B15003_001E"] * 100

# Select  columns
df_ed = df_ed[["county_fips", "pct_bachelors"]]

df_ed.head()

   county_fips  pct_bachelors
0        55001      15.051082
1        55003      19.056707
2        55005      20.593484
3        55007      33.522820
4        55009      31.784420

In [101]:
#download census state-level demographic data
from censusdis import states

VARIABLES2 = ["NAME", TOT_POP, MED_HH_INC, WHITE_ALONE, 
              "B15003_001E",  # Total population 25 years and over
              "B15003_022E",  # Bachelor's degree
              "B15003_023E",  # Master's degree
              "B15003_024E",  # Professional school degree
              "B15003_025E"   # Doctorate degree
]

df_state = ced.download(
    DATASET,
    YEAR,
    VARIABLES2,
    state=states.WI
)



# Calculate percentage
df_state["pct_bachelors"] = (
    df_state["B15003_022E"] + df_state["B15003_023E"] + df_state["B15003_024E"] + df_state["B15003_025E"]
) / df_state["B15003_001E"] * 100



df_state = df_state.drop(columns=[  "B15003_001E",  # Total population 25 years and over
              "B15003_022E",  # Bachelor's degree
              "B15003_023E",  # Master's degree
              "B15003_024E",  # Professional school degree
              "B15003_025E" ])

df_state.head()

df_state.columns = ['STATE', 'NAME', 'TOT_POP', 'MED_HH_INC', 'WHITE_POP', "pct_bachelors"]


df_state['county_fips'] = [55000]

df_state.head()

df_counties2 = df_counties2.merge(df_ed, how = "left")

df_demographics =  pd.concat([df_state, df_counties2])

#df_demographics = df_demographics.merge(df_ed, how = "left")

df_demographics.head()

,STATE,NAME,TOT_POP,MED_HH_INC,WHITE_POP,pct_bachelors,county_fips
0,55,Wisconsin,5806975,63293,4895065,30.801373,55000
0,NaN,"Ashland County, Wisconsin",15524,47869,13025,19.056707,55003
1,NaN,"Barron County, Wisconsin",45182,52346,42535,20.593484,55005
2,NaN,"Brown County, Wisconsin",262559,64728,220020,31.784420,55009
3,NaN,"Buffalo County, Wisconsin",13087,58364,12631,19.623185,55011

In [102]:
df_merge = df_f.merge(df_counties, how='left')
#type(df_counties)

#Calculate the percentage of people in each county who swung toward Trump in 2024 compared to 2020
#df_merge["swing_pc"] = df_merge["DIFF_PRE_REP_20to24"]/df_merge["B01003_001E"]*100

#Calcuate the percent white
df_merge["white_pct"] = df_merge["WHITE_POP"]/df_merge["TOT_POP"]*100

df_merge.head()

NameError: name 'df_f' is not defined

In [ ]:
#merge XYZ data with demographics data
df_bars = df_swings.merge(df_demographics, how='left')
df_bars["white_pct"] = df_merge["WHITE_POP"]/df_merge["TOT_POP"]*100


df_bars.head(11)

,county_fips,county,Republican swing,Swing_party,NAME,TOT_POP,MED_HH_INC,WHITE_POP,white_pct
0,55065,LAFAYETTE,3.334745,Republican,"Lafayette County, Wisconsin",16682,61070,16069,82.629102
1,55003,ASHLAND,3.093371,Republican,"Ashland County, Wisconsin",15524,47869,13025,90.293480
2,55043,GRANT,3.073961,Republican,"Grant County, Wisconsin",51570,54144,49592,57.117512
3,55049,IOWA,3.016880,Republican,"Iowa County, Wisconsin",23632,68714,22649,95.185169
4,55000,STATE of WISCONSIN,NaN,STATEWIDE,Wisconsin,5806975,63293,4895065,83.798308
5,55011,BUFFALO,2.635806,Republican,"Buffalo County, Wisconsin",13087,58364,12631,90.718190
6,55121,TREMPEALEAU,2.532418,Republican,"Trempealeau County, Wisconsin",29525,59606,27257,85.429331
7,55131,WASHINGTON,-0.847549,Democrat,"Washington County, Wisconsin",135529,80839,127569,91.382229
8,55089,OZAUKEE,-0.759002,Democrat,"Ozaukee County, Wisconsin",89179,84394,82695,83.362525
9,55133,WAUKESHA,-0.480531,Democrat,"Waukesha County, Wisconsin",402637,88985,365265,89.220624
10,55029,DOOR,-0.394115,Democrat,"Door County, Wisconsin",27621,61765,26484,90.911535

In [28]:

df_merge.to_csv('data.csv', index=False)
df_bars.to_csv('data_bars.csv', index = False)