In [38]:
## Packages
import pandas as pd

In [39]:
## Import data stored in Git Hub
df_raw = pd.read_csv("election-results-2012-2024.csv")
df_raw.head(10)

,level,county,county_fips,ctv,municipality,MCD_FIPS,reporting_unit,rep_unit_2024,USSDEM24,PREDEM24,...,PREDEM16,PREREP16,GOVDEM14,GOVREP14,USSDEM12,GOVDEM12,GOVREP12,PREDEM12,PREREP12,USSREP12
0,reporting unit,ADAMS,55001,T,ADAMS,5500100300,TOWN OF ADAMS WARDS 1-3,ADAMS - TOWN OF ADAMS WARDS 1-3,286,264,...,207.682464,377.796209,233.625592,258.526066,335.909953,239.781991,280.682464,358.037915,270.625592,260.611374
1,reporting unit,ADAMS,55001,T,BIG FLATS,5500107300,TOWN OF BIG FLATS WARDS 1 & 2,ADAMS - TOWN OF BIG FLATS WARDS 1-2,202,177,...,169.000000,300.000000,187.000000,205.000000,281.000000,168.000000,215.000000,282.000000,209.000000,180.000000
2,reporting unit,ADAMS,55001,T,COLBURN,5500116075,TOWN OF COLBURN WARD 1,ADAMS - TOWN OF COLBURN WARD 1,45,37,...,42.000000,85.000000,43.000000,59.000000,69.000000,46.000000,60.000000,63.000000,58.000000,45.000000
3,reporting unit,ADAMS,55001,T,DELL PRAIRIE,5500119575,TOWN OF DELL PRAIRIE WARDS 1 & 2,ADAMS - TOWN OF DELL PRAIRIE WARDS 1-3,405,379,...,301.000000,474.000000,310.000000,359.000000,406.000000,277.000000,387.000000,429.000000,411.000000,408.000000
4,reporting unit,ADAMS,55001,T,EASTON,5500122000,TOWN OF EASTON WARD 1,ADAMS - TOWN OF EASTON WARD 1,223,199,...,169.000000,336.000000,171.000000,209.000000,254.000000,175.000000,204.000000,270.000000,237.000000,234.000000
5,reporting unit,ADAMS,55001,T,JACKSON,5500137625,TOWN OF JACKSON WARDS 1 & 2,ADAMS - TOWN OF JACKSON WARDS 1-2,297,277,...,225.000000,314.000000,214.000000,241.000000,297.000000,202.000000,263.000000,310.000000,253.000000,259.000000
6,reporting unit,ADAMS,55001,T,LEOLA,5500143425,TOWN OF LEOLA WARD 1,ADAMS - TOWN OF LEOLA WARD 1,37,34,...,18.000000,116.000000,33.000000,88.000000,51.000000,19.000000,98.000000,50.000000,102.000000,96.000000
7,reporting unit,ADAMS,55001,T,LINCOLN,5500144250,TOWN OF LINCOLN WARD 1,ADAMS - TOWN OF LINCOLN WARD 1,70,67,...,76.000000,98.000000,72.000000,69.000000,82.000000,64.000000,69.000000,84.000000,80.000000,69.000000
8,reporting unit,ADAMS,55001,T,MONROE,5500153725,TOWN OF MONROE WARD 1,ADAMS - TOWN OF MONROE WARD 1,127,120,...,102.000000,129.000000,101.000000,114.000000,145.000000,101.000000,132.000000,135.000000,126.000000,110.000000
9,reporting unit,ADAMS,55001,T,NEW CHESTER,5500156525,TOWN OF NEW CHESTER WARDS 1-3,ADAMS - TOWN OF NEW CHESTER WARDS 1-3,192,166,...,138.000000,247.000000,147.000000,153.000000,231.000000,160.000000,168.000000,266.000000,160.000000,175.000000

In [74]:
## Collapse data by FIPS code to get county-level counts
df_c = df_raw.groupby(['county_fips', 'county'], as_index = False).sum()
## Remove unnecessary columns
df_c = df_c.drop(columns = ['level', 'ctv', 'municipality', 'MCD_FIPS', 'reporting_unit', 'rep_unit_2024'])
## Round to nearest whole number
df_c = df_c.round(0)
df_c.head(10)

,county_fips,county,USSDEM24,PREDEM24,PREREP24,USSREP24,GOVDEM22,GOVREP22,USSDEM22,USSREP22,...,PREDEM16,PREREP16,GOVDEM14,GOVREP14,USSDEM12,GOVDEM12,GOVREP12,PREDEM12,PREREP12,USSREP12
0,55001,ADAMS,4795,4434,7750,7539,3854.0,5844.0,3640.0,6188.0,...,3739.0,5952.0,3754.0,4294.0,5156.0,3652.0,4489.0,5537.0,4634.0,4394.0
1,55003,ASHLAND,4775,4612,4190,3844,4034.0,2905.0,3903.0,3074.0,...,4226.0,3303.0,4150.0,2333.0,5306.0,4174.0,2598.0,5399.0,2820.0,2912.0
2,55005,BARRON,9352,8941,16744,16399,7552.0,12246.0,7121.0,12928.0,...,7889.0,13614.0,6832.0,9696.0,10644.0,7015.0,10420.0,10890.0,11443.0,10805.0
3,55007,BAYFIELD,6260,6107,4860,4697,5367.0,3843.0,5183.0,4082.0,...,4953.0,4124.0,4888.0,3075.0,6017.0,4889.0,3269.0,6033.0,3603.0,3476.0
4,55009,BROWN,67763,67910,79115,76706,53889.0,58988.0,51423.0,62224.0,...,53384.0,67212.0,40752.0,58410.0,60410.0,41239.0,61970.0,62528.0,64837.0,61839.0
5,55011,BUFFALO,2913,2765,5213,4898,2391.0,3638.0,2201.0,3907.0,...,2522.0,4044.0,2267.0,3169.0,3366.0,2148.0,3403.0,3570.0,3364.0,3284.0
6,55013,BURNETT,3731,3676,7005,6743,2964.0,5061.0,2834.0,5362.0,...,2949.0,5410.0,2615.0,3868.0,3996.0,2536.0,3998.0,3986.0,4550.0,4288.0
7,55015,CALUMET,12844,12922,19474,19061,9935.0,14828.0,9444.0,15466.0,...,9642.0,15367.0,7285.0,14086.0,10989.0,7515.0,15004.0,11489.0,14539.0,14053.0
8,55017,CHIPPEWA,14879,14575,23414,22201,11995.0,16794.0,11070.0,17697.0,...,11887.0,17916.0,10402.0,13765.0,14774.0,10419.0,14877.0,15237.0,15322.0,14677.0
9,55019,CLARK,4822,4509,10485,9918,3798.0,7691.0,3452.0,8182.0,...,4221.0,8652.0,3848.0,7409.0,6159.0,3618.0,8133.0,6172.0,7412.0,6875.0

In [76]:
## Calculate new colums 

#Votes for Kamala Harris 2024 - Tammy Baldwin2024
df_c['DIFFDEM24'] = df_c['PREDEM24'] - df_c['USSDEM24']
#Votes for Donald Trump 2024 - Eric Hovde 2024
df_c['DIFFREP24'] = df_c['PREREP24'] - df_c['USSREP24'] 
#Votes for Kamala Harris 2024 - Joe Biden 2020
df_c['DIFF_PRE_DEM_24to20'] = df_c['PREDEM24'] - df_c['PREDEM20']
#Votes for Donald Trump 2024 - Donald Trump Trump 2020
df_c['DIFF_PRE_REP_20to24'] = df_c['PREREP24'] - df_c['PREREP20']



#Select the columns of interest, sort by preferred variable DIFF_PRE_REP_20to24
df_f = df_c[['county_fips', 'county', 'DIFFDEM24', 'DIFFREP24', 'DIFF_PRE_DEM_24to20', 'DIFF_PRE_REP_20to24']].sort_values(by = ['DIFF_PRE_REP_20to24'], ascending = False).head(10)

df_f.info()
df_f.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 12 to 44
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   county_fips          10 non-null     int64
 1   county               10 non-null     object
 2   DIFFDEM24            10 non-null     int64
 3   DIFFREP24            10 non-null     int64
 4   DIFF_PRE_DEM_24to20  10 non-null     float64
 5   DIFF_PRE_REP_20to24  10 non-null     float64
dtypes: float64(2), int64(3), object(1)
memory usage: 560.0+ bytes

,county_fips,county,DIFFDEM24,DIFFREP24,DIFF_PRE_DEM_24to20,DIFF_PRE_REP_20to24
12,55025,DANE,294,692,13834.0,6656.0
31,55063,LA CROSSE,-260,1501,1162.0,3563.0
40,55079,MILWAUKEE,880,6317,-1271.0,3527.0
55,55109,ST. CROIX,78,693,678.0,3328.0
4,55009,BROWN,147,2409,2397.0,3241.0
67,55133,WAUKESHA,2694,-823,4549.0,3092.0
53,55105,ROCK,-436,2119,-16.0,3079.0
64,55127,WALWORTH,279,906,354.0,2730.0
29,55059,KENOSHA,-121,2313,-368.0,2503.0
44,55087,OUTAGAMIE,242,1750,1770.0,2441.0

In [87]:
## Chart 1
#pip install "altair[all]" in linux
import altair as alt



alt.Chart(df_f).mark_bar().encode(
    x="DIFF_PRE_REP_20to24",
    y=alt.Y("county").sort("x")
)

alt.Chart(...)